from openai_api import chat_with_chatgpt
from data_scraper.cwa_opendata_scraper import get_cities_weather
from computer_vision.imgur_uploader import init_imgur_client, upload_to_imgur
from computer_vision.mediapipe_cv_tools import init_face_detector, detect_face_with_content_drawing
from computer_vision.image_format_converter import convert_from_cv2_to_bytes

face_detection_model = init_face_detector('computer_vision/cv_models/blaze_face_short_range.tflite')
