name: Build and deploy Python app to Azure Web App - linebot

on:
  workflow_dispatch:
  push:
    branches:
      - master
env:
  PYTHON_VERSION: '3.12'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # - name: Create and start virtual environment
      #   run: |
      #     python -m venv venv
      #     source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      # https://github.com/azure/appservice-build/tree/v2/?tab=readme-ov-file#sample-workflow-to-build-and-deploy-an-azure-web-app
      - name: Building web app
        uses: azure/appservice-build@v2
        with:
          platform-version: "Python ${{ env.PYTHON_VERSION }}"
        
      # # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      # - name: Zip artifact for deployment
      #   run: zip release.zip ./* -r

      # - name: Upload artifact for deployment jobs
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: python-app
      #     path: |
      #       release.zip
      #       !venv/

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'linebot'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
