name: Build and deploy Python app to Azure Web App - linebot

on:
  workflow_dispatch:
  push:
    branches:
      - master
env:
  PYTHON_VERSION: '3.12'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      # # oryx 支援 python 版本太舊 (python 3.8)
      # # https://github.com/azure/appservice-build/tree/v2/?tab=readme-ov-file#sample-workflow-to-build-and-deploy-an-azure-web-app
      # - name: Building web app
      #   uses: azure/appservice-build@v2
      #   with:
      #     platform: python
      #     platform-version: ${{ env.PYTHON_VERSION }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'linebot'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
